### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#742] opened 2016-07-10 20:37 UTC
I get this message:
```
Doctrine Exception: Schema-Tool failed with Error 'An exception occurred while executing 'ALTER TABLE mu_muimage_album ADD CONSTRAINT FK_28988805727ACA70 FOREIGN KEY (parent_id) REFERENCES mu_muimage_album (id)': SQLSTATE[HY000]: General error: 1005 Can't create table 'd01ee189.#sql-983_36825b' (errno: 150)' while executing DDL: ALTER TABLE mu_muimage_album ADD CONSTRAINT FK_28988805727ACA70 FOREIGN KEY (parent_id) REFERENCES mu_muimage_album (id)
Initialization of MUMUImageModule failed!

```

**Comment by Guite** [comment] 2016-07-18 06:34
Could it be that this foreign key already existed in your database from an earlier installation attempt?

**Comment by Portugao** [comment] 2016-07-18 07:07
I deleted all tables, same error. Maybe I have an error in my model....

**Comment by Guite** [comment] 2016-07-18 07:08
Deleting the tables does not necessarily delete all foreign constraints, too. Can you retest using a fresh database maybe?

**Comment by Portugao** [comment] 2016-07-18 07:19
I will try.

**Comment by Portugao** [comment] 2016-07-22 15:06
Me again. I just tried an install with a fresh zikula installation.
Sorry. I get the same error.

**Comment by Guite** [comment] 2016-07-22 15:18
And you used a fresh new database?

**Comment by Portugao** [comment] 2016-07-22 15:23
Yes. Deleted all tables.

**Comment by Guite** [comment] 2016-07-22 15:33
As I wrote above:

> Deleting the tables does not necessarily delete all foreign constraints, too. Can you retest using a fresh database maybe?

**Comment by Portugao** [comment] 2016-07-22 15:38
Sure.

**Comment by Guite** [comment] 2016-07-22 15:54
Confirmed. There is indeed a problem.

**Comment by Guite** [comment] 2016-07-22 16:10
The reason for this error is that `id` and `parent_id` have different data types.

* `id` is `INT(11)`
* `parentId` is `BIGINT(20)`

After I manually changed `parentId` to `INT(11)` I could add the foreign key without problems.
If you set the `parentId` field's length to `10` everything should work.

See https://github.com/Guite/MostGenerator/blob/master/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/extensions/ModelExtensions.xtend#L716 for the details.

**Comment by Guite** [comment] 2016-07-22 16:23
Added a note in https://github.com/Guite/MostHelp/commit/c1f1e077d71e2dffe1f2e74eab9135f4119501d4 which is now shown at http://modulestudio.de/documentation/c/55-GeneratorReference#GenRefAbstractIntegerField

**Comment by Portugao** [comment] 2016-07-22 16:33
:+1: 
Thx a lot.

**Comment by Portugao** [comment] 2016-07-22 16:42
MOST does not accept a length of 10, I get an error message. So I have to do manually.

**Comment by Guite** [comment] 2016-07-22 16:46
Please post the validation error message. Probably something needs to be adjusted here.

**Comment by Portugao** [comment] 2016-07-22 16:55
```

Das Feld parent_id muss ein Integer-Feld mit einer Länge von 11 sein.

**Comment by Portugao** [comment] 2016-07-22 16:58
I have to say that the parent_id field is an integer field.

**Comment by Guite** [comment] 2016-07-22 16:58
Okay, I think the better fix is the use `integer` instead of `bigint` for a length of 11. Going to change that.

**Comment by Guite** [comment] 2016-07-22 17:00
Fixed in https://github.com/Guite/MostGenerator/commit/3c938bfc21191f8f5a833a0718581ad3d653973b and https://github.com/Guite/MostHelp/commit/eb6d888c2e4b9ff1131c4a09bbaafa7b01909bff

**Closed by Guite** 2016-07-22 17:00 UTC
Labels: doctrine2, feedback, zk 1.4.x

**Comment by Guite** [comment] 2016-07-22 17:32
Webgen is updated, you can now regenerate which should include this change.

**Comment by Portugao** [comment] 2016-07-22 17:34
:+1:

**Comment by Portugao** [comment] 2016-07-22 20:09
Hmmhmm...
I'm confused. In version 1.3.0 of MUImage I find:

```
        /**
         * @ORM\Column(type="bigint", nullable=true)
         * @var integer $parent_id.
         */
        protected $parent_id = 0;
```
Is it integer or bigint?

**Comment by Guite** [comment] 2016-07-23 05:03
Fixed in latest webgen:
```
    /**
     * @ORM\Column(type="integer", nullable=true)
     * @var integer $parent_id.
     */
    protected $parent_id = 0;
```

**Comment by Portugao** [comment] 2016-07-23 12:42
Thx. This issue is gone; and there is another....
#745
