### ISSUE TITLE
Module installation failing on build#37

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1141] opened 2017-09-18 16:36 UTC
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [latest git]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.x-git]
| PHP Version            | [5.6.x]

### Expected behavior
module installs

### Actual behavior
Initialization of ByblosByblosModule failed!
Catchable Fatal Error: Argument 2 passed to Byblos\ByblosModule\Helper\Base\AbstractUploadHelper::__construct() must be an instance of Symfony\Component\Filesystem\Filesystem, instance of Symfony\Component\HttpFoundation\Session\Session given, called in /var/www/vhosts/.../httpdocs/modules/Byblos/ByblosModule/Base/AbstractByblosModuleInstaller.php on line 38 and defined

### Steps to reproduce
Zikula new install, build#37, reinstall module that worked on older zikula builds, all system modules and Dizkus, Scribite are installing

**Comment by Portugao** [comment] 2017-09-18 16:42
Seems to be duplicate of https://github.com/Guite/MostGenerator/issues/1137.....

**Comment by Guite** [comment] 2017-09-18 16:59
Yes, it is already fixed. Ensure you have the latest staging update installed by verifying your ModuleStudio preferences (ignore updates should be disabled and staging updates should be enabled).

**Closed by Guite** 2017-09-18 16:59 UTC

**Comment by ThiloWitt** [comment] 2017-09-22 05:43
Thanks, after ModulStudio update it works
