### ISSUE TITLE
Ampersand handling

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#692] opened 2015-09-19 00:01 UTC
I am using MOST 06.2, so this might be an old issue.

I am doing some heavy data processing while importing data.  I am finding repeatedly, in many entities, that text values containing ampersands aren't handled nicely.  The gist of the problem is that the data is initially persisted correctly, for example "A & B" as "A &amp; B".  However if that entity is gotten, manipulated and then persisted again (perhaps in a cascade) it is saved as "A &amp;amp; B".  If it happens many times, it gets really ridiculous and causes validation errors related to string length.  The latest example is a URL string query value, for example:

http://www.domain.com/WebSync/Pages/Team/TeamSchedule.aspx?association=10&amp;amp;amp;amp;amp;amp;amp;sg=MBB&amp;amp;amp;amp;amp;amp;amp;team=389

As a workaround, I am html_entity_decode() on these values after they are gotten, so that they will be persisted correctly.  But I have now accumulated a long list of values I have to do this to.

**Comment by Guite** [comment] 2015-09-19 07:31
Maybe an easier (central) workaround until the issue is solved: lookup the `formatTextualField` method in the base entity class. There you will find this condition:

```
                if ($currentFunc == 'edit') {
                    // apply no changes when editing the content
                    return;
                }
```

Change it to:

```
                if (in_array($currentFunc, array('edit', 'yourImportFunction'))) {
                    // apply no changes when editing the content
                    return;
                }
```

**Comment by Guite** [comment] 2015-09-19 07:32
Or even better: override it in the child class like this:

```
                if ($currentFunc == 'yourImportFunction') {
                    return;
                }

                return parent::formatTextualField($fieldName, $currentFunc, $usesCsvOutput, $allowZero);
```

**Comment by cmfcmf** [comment] 2015-09-19 11:46
refs https://github.com/Guite/MostGenerator/issues/624

**Comment by robbrandt** [comment] 2015-10-01 06:01
Is there a function that will clean up an entire object?  I have some entities with one to many relations that of course have entire collections in them, and cascade persist.  So keeping them "clean" is becoming incredibly unwieldy doing it one field at a time.

**Comment by Guite** [comment] 2015-12-08 12:06
Fixed in f4f1cd00ee535ea96c864b8994377bd4fe0f3938

**Comment by robbrandt** [comment] 2016-08-03 13:41
@guite: in 0.7.0, is there a more complete fix implemented than the workaround in https://github.com/Guite/MostGenerator/commit/f4f1cd00ee535ea96c864b8994377bd4fe0f3938?  There were other characters than & involved, and I need to know if I will have to maintain strings here.

**Comment by Guite** [comment] 2016-08-03 14:47
No there isn't a better solution implemented yet. If you come up with something please propose it :-)

**Comment by Guite** [comment] 2016-08-05 05:07
Maybe the whole method is not required anymore in 1.4.3+ modules, because Twig is now used which should do output sanitising automatically. We need to recheck this.

**Comment by Guite** [comment] 2016-08-17 14:25
Disabled the method for 1.4.x in 0d24a569222270b6b0f9f49e84b5dc370d3621f6

**Closed by Guite** 2016-08-17 14:25 UTC
Labels: bug
