### ISSUE TITLE
Make the default field calculatable

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#350] opened 2013-08-05 19:48 UTC
If it is a text field it should be possible to add a text variable. If it is a numeric field it should be possible to make some calculation with numeric variables.

It is similar to #263

**Comment by Guite** [comment] 2016-09-14 14:55
refs #152

**Comment by Guite** [comment] 2017-05-03 15:26
Closed in favour / as duplicate of: #887, #263, #152

**Closed by Guite** 2017-05-03 15:26 UTC
Labels: architecture, feature, language, tooling
