### ISSUE TITLE
add twig template generation (remove Smarty)

### ISSUE THREAD

**Issue by craigh** [Guite/MostGenerator#699] opened 2015-10-04 11:57 UTC
Core-1.4.1 fully supports Twig templates and Symfony Controllers. MOST should migrate to this asap.

**Comment by Guite** [comment] 2015-11-10 17:20
See also
https://github.com/Guite/MostGenerator/issues/571
https://github.com/zikula/core/pull/2634

**Comment by Guite** [comment] 2015-11-12 15:41
Closed as duplicate of #571

**Closed by Guite** 2015-11-12 15:41 UTC
Labels: zk 1.4.x
