### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1127] opened 2017-08-31 15:14 UTC
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.x-git
| PHP Version | 5.6.x

### Expected behavior
no error

### Actual behavior
```
in vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\File\File.php at line 37   -
    public function __construct($path, $checkPath = true)
    {
        if ($checkPath && !is_file($path)) {
            throw new FileNotFoundException($path);
        }
        parent::__construct($path);
at File ->__construct ('DSC003292.jpg') 
in modules\MU\TestAppModule\Listener\Base\AbstractEntityLifecycleListener.php at line 226   +
at AbstractEntityLifecycleListener ->preUpdate (object(PreUpdateEventArgs)) 
in vendor\symfony\symfony\src\Symfony\Bridge\Doctrine\ContainerAwareEventManager.php at line 63   +
at ContainerAwareEventManager ->dispatchEvent ('preUpdate', object(PreUpdateEventArgs)) 
in vendor\doctrine\orm\lib\Doctrine\ORM\Event\ListenersInvoker.php at line 117   +
at ListenersInvoker ->invoke (object(ClassMetadata), 'preUpdate', object(PageEntity), object(PreUpdateEventArgs), '4') 
in vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php at line 1060   +
at UnitOfWork ->executeUpdates (object(ClassMetadata)) 
in vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php at line 384   +
at UnitOfWork ->commit (null) 
in vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php at line 356   +
at EntityManager ->flush () 
in modules\MU\TestAppModule\Helper\Base\AbstractTranslatableHelper.php at line 216   +
at AbstractTranslatableHelper ->processEntityAfterEditing (object(PageEntity), object(Form), object(EntityManager)) 
in modules\MU\TestAppModule\Form\Handler\Common\Base\AbstractEditHandler.php at line 655   +
at AbstractEditHandler ->processTranslationsForUpdate () 
in modules\MU\TestAppModule\Form\Handler\Common\Base\AbstractEditHandler.php at line 615   +
at AbstractEditHandler ->handleCommand (array()) 
in modules\MU\TestAppModule\Form\Handler\Page\Base\AbstractEditHandler.php at line 161   +
at AbstractEditHandler ->handleCommand () 
in modules\MU\TestAppModule\Form\Handler\Common\Base\AbstractEditHandler.php at line 428   +
at AbstractEditHandler ->processForm (array('routeArea' => 'admin', 'thumbRuntimeOptions' => array('pageMyImage' => array('thumbnail' => array('size' => array('240', '180'), 'mode' => 'inset', 'extension' => null))), 'relationThumbRuntimeOptions' => array('thumbnail' => array('size' => array('100', '75'), 'mode' => 'inset', 'extension' => null)), 'featureActivationHelper' => object(FeatureActivationHelper))) 
in modules\MU\TestAppModule\Form\Handler\Page\Base\AbstractEditHandler.php at line 47   +
at AbstractEditHandler ->processForm (array('routeArea' => 'admin', 'thumbRuntimeOptions' => array('pageMyImage' => array('thumbnail' => array('size' => array('240', '180'), 'mode' => 'inset', 'extension' => null))), 'relationThumbRuntimeOptions' => array('thumbnail' => array('size' => array('100', '75'), 'mode' => 'inset', 'extension' => null)), 'featureActivationHelper' => object(FeatureActivationHelper))) 
in modules\MU\TestAppModule\Controller\Base\AbstractPageController.php at line 266   +
at AbstractPageController ->editInternal (object(Zikula_Request_Http), true) 
in modules\MU\TestAppModule\Controller\Base\AbstractPageController.php at line 227   +
at AbstractPageController ->adminEditAction (object(Zikula_Request_Http)) 
in modules\MU\TestAppModule\Controller\PageController.php at line 189   +
at PageController ->adminEditAction (object(Zikula_Request_Http))
at call_user_func_array (array(object(PageController), 'adminEditAction'), array(object(Zikula_Request_Http))) 
in vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php at line 144   +
at HttpKernel ->handleRaw (object(Zikula_Request_Http), '1') 
in vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php at line 64   +
at HttpKernel ->handle (object(Zikula_Request_Http), '1', true) 
in vendor\symfony\symfony\src\Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel.php at line 69   +
at ContainerAwareHttpKernel ->handle (object(Zikula_Request_Http), '1', true) 
in vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php at line 185   +
at Kernel ->handle (object(Zikula_Request_Http)) 
in index.php at line 23   +
```

### Steps to reproduce
Take fresh module with translatable field and no mandatory upload
try to create an item.

**Comment by Guite** [comment] 2017-08-31 15:26
> with translatable field and no mandatory upload

Is the upload field translatable?

Can you attach the mostapp file here?

**Comment by Portugao** [comment] 2017-08-31 15:37
No
Yes
Mom

**Comment by Portugao** [comment] 2017-08-31 15:38
[TestApp.zip](https://github.com/Guite/MostGenerator/files/1267641/TestApp.zip)

**Comment by Portugao** [comment] 2017-08-31 15:49
Complicated?

**Comment by Guite** [comment] 2017-08-31 15:50
don't know yet, need some time to reproduce; probably possible tomorrow

**Comment by Guite** [comment] 2017-08-31 17:05
Can't reproduce. It seems all working. Closing. Please update your core and give me a shout if the error won't go away.

**Comment by Guite** [comment] 2017-08-31 17:54
I have an idea...

**Closed** 2017-08-31 18:43 UTC
Labels: bug
