### ISSUE TITLE
Scribite plugin causes error

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1086] opened 2017-07-20 15:11 UTC
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | [Windows|Linux|MacOS]
| Zikula Target in Model | ZK15
| Zikula Version         | 1.5.x-git
| PHP Version            | 5.6.x

### Expected behavior
Loading of CKEditor

### Actual behavior
Resource not found:
```

ckeditor.js:249 Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "muimagemodule" was not found at "http://zik15.localhost/modules/MU/ImageModule/Resources/docs/scribite/plugins/CKEditor/vendor/ckeditor/plugins/muimagemodule/plugin.js?t=H0CG".
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:249)
    at f (ckeditor.js:244)
    at Array.B (ckeditor.js:244)
    at u (ckeditor.js:244)
    at ckeditor.js:245
```

### Steps to reproduce
Take actual repository of Image.

**Comment by Guite** [comment] 2017-07-20 16:02
Closing as won't fix. The problem was caused by the plugins not being in place.

**Closed** 2017-07-20 16:51 UTC
Labels: integration
