### ISSUE TITLE
[1.4.x] 1:n relation - dropdown in target edit form gives error

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#683] opened 2015-07-21 19:23 UTC
```
Notice: Array to string conversion in domain/lib/legacy/Zikula/Form/AbstractStyledPlugin.php on line 75
```
I cannot send the form.

**Comment by Guite** [comment] 2015-11-20 13:51
Can you tell me how to reproduce this? Which entity did you edit from which model?

**Comment by Portugao** [comment] 2015-11-30 16:48
Should be the model of MUPolls saved in the webgen.

**Comment by Guite** [comment] 2015-12-10 13:26
Blocked by #416

**Comment by craigh** [comment] 2015-12-10 14:10
![screen shot 2015-12-10 at 9 09 11 am](https://cloud.githubusercontent.com/assets/350048/11717308/b766fffc-9f1d-11e5-90ab-2e3cdd2ee808.png)

![250px-flag_of_germany svg](https://cloud.githubusercontent.com/assets/350048/11717321/d5c38f42-9f1d-11e5-90d0-7b915e866cc5.png)

tell me you didn't do that on purpose :stuck_out_tongue_winking_eye:

**Comment by Guite** [comment] 2015-12-10 14:17
LOL at least we now know how this flag was created :-)

**Comment by craigh** [comment] 2015-12-10 14:20
yes, it was a bug report! :laughing:

**Comment by cmfcmf** [comment] 2015-12-10 15:54
:de:

**Comment by Guite** [comment] 2015-12-28 13:18
Closing this one, because editing is completely changed for 1.4 apps in #416 anyway.

**Closed by Guite** 2015-12-28 13:18 UTC
Labels: bug, relations
