### ISSUE TITLE
[1.4.x] Calling the permissions module gives error

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#757] opened 2016-07-25 09:46 UTC
```
Catchable Fatal Error: Argument 1 passed to MU\MUImageModule\Block\Base\ItemListBlock::__construct() must be an instance of MU\MUImageModule\Block\Base\AbstractBundle, instance of MU\MUImageModule\MUMUImageModule given, called in /domain/system/BlocksModule/Api/BlockFactoryApi.php on line 84 and defined
```

**Comment by Guite** [comment] 2016-07-25 09:47
Duplicate of #756

**Closed by Guite** 2016-07-25 09:47 UTC

**Comment by Portugao** [comment] 2016-07-25 09:50
Oh; sorry.
