### ISSUE TITLE
New entry - No further editing after clicking "Defer" instead of "Submit"

### ISSUE THREAD

**Issue by DirkThiele** [Guite/MostGenerator#1203] opened 2018-09-29 13:27 UTC
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [latest git]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.0.11]
| PHP Version            | [7.1.19-nmm1]

### Expected behavior
User with Permission "Edit" wants to Defer an entry for later editing.

### Actual behavior
After clicking "Defer" the entry can be shown with url parameter `?own=1` but editing is not possible.

### Steps to reproduce
Use a user with permission as described above.
Create new entry and click "Defer" instead od "Submit"
Entity needs to have a tray.

**Comment by Guite** [comment] 2018-09-29 13:37
Note: this is with `ownerPermission = true`.

**Comment by Guite** [comment] 2020-01-02 08:30
Can't reproduce this with the latest generator anymore. I am closing this ticket as the problem has probably already been fixed.
If you still experience this problem please contact me in Slack so we can further investigate it together.

**Closed by Guite** 2020-01-02 08:30 UTC
Labels: workflows

**Comment by DirkThiele** [comment] 2020-01-02 16:34
I will check, thank you!
