### ISSUE TITLE
Possible Workflow error

### ISSUE THREAD

**Issue by craigh** [Guite/MostGenerator#1237] opened 2020-06-20 20:51 UTC
I get the following error when having several MOST-generated modules installed at the same time.

1. manually delete the entire cache
2. `bin/console`

> In StateMachineValidator.php line 40:
>  A transition from a place/state must have an unique name. Multiple transitions named "defer" from place/state "initial" were found on StateMachine "zikulapagesmodule_none".

sending `bin/console` a second time makes the error disappear... so I'm not sure what's happening.

**Comment by Guite** [comment] 2020-06-21 08:12
My first guess is this is not related to having several extensions installed concurrently, because all workflows get a unique name based on the corresponding extension name. Also the error message clearly shows that the problem relates to the workflow details.

It _could_ be related to some changes in Symfony 5.1 - not sure yet though.

Unfortunately I can not reproduce it yet.
Which MOST-based extensions do you have (in addition to Routes)? Are all of them actually also installed (regarding the extension's state)?

I also looked how `StateMachineValidator` works. If just collects all transitions of a given workflows and [checks that there are no duplicates](https://github.com/symfony/workflow/blob/master/Validator/StateMachineValidator.php#L39).

The [zikulapagesmodule_none](https://github.com/zikula-modules/Pages/blob/master/src/extensions/Zikula/PagesModule/Resources/workflows/none.yaml) workflow looks fine with regards to this.

Could it be possible somehow that you have two files containing this workflow (e.g. in `config`, `overrides` or another location)? Could you maybe search for "zikulapagesmodule_none" to exclude this theory?

**Comment by craigh** [comment] 2020-06-21 11:03
I had Pages and a private test module I had created. Pages was installed I think. I've since removed all of them as I was testing the Formicula installer. 

I have no other files containing workflows. A search of 'zikulapagesmodule_none' resulted in nothing found.

> If just collects all transitions of a given workflows and checks that there are no duplicates

I assumed this and thought it possible that generated modules might _all_ have the "defer" or "initial" state. But I don't know anything about it.

It is possible this was just an artifact of the debugging I was doing. I wasn't sure, so I thought I would bring it to your attention.

**Comment by Guite** [comment] 2020-06-21 11:05
> generated modules might all have the "defer" or "initial" state

They do. But they all use different (distinct) workflow names.

> It is possible this was just an artifact of the debugging I was doing. I wasn't sure, so I thought I would bring it to your attention.

Thank you!
I will close this for now, but keep it in mind. In case you see this again maybe please keep me updated.

**Closed by Guite** 2020-06-21 11:05 UTC
Labels: bug, feedback
